### ISSUE TITLE
add "new" UI

### ISSUE THREAD

**Issue by gjvanderheiden** [AppJail-makejails/inventree#2]
Could the Inventree appjail be extended with the "new" frontend?
Something in the lines of:

```
CMD mkdir -p /inventree/src/src/backend/InvenTree/web/static
CMD fetch -o /tmp/inventree-frontend-build.zip https://github.com/inventree/InvenTree/releases/download/${inventree_version}/frontend-build.zip
CMD unzip -qq /tmp/inventree-frontend-build.zip -d /inventree/src/src/backend/InvenTree/web/static/web
CMD rm -f /tmp/inventree-frontend-build.zip
```

I tried to build the jail it myself, to make a PR, but after a few hours I gave up. (I also tried with appjail-reproduce).

This is in the install script for debian too, but I'm not sure this is enough. I really thought I got this working with logging in into the jail, but I can't reproduce it.

The new frontend has some features that aren't in the current one.

**Comment by DtxdF** [comment]
I'll make a change in the Makejail to install (optionally through a parameter) this frontend. You can access it through `<http://<host-ip>:<port>/platform>`. If you want to use this frontend, you can use the following Makejail and apply it to an existing InvenTree installation:

**apply-frontend.makejail**:

```
STAGE apply

CMD --juser inventree inventree_version=`sh -c "cd ~/src; invoke version | grep -Ee '^InvenTree   ' | cut -d' ' -f4"`; \
            mkdir -p /inventree/src/src/backend/InvenTree/web/static; \
            fetch -o /tmp/inventree-frontend-build.zip https://github.com/inventree/InvenTree/releases/download/${inventree_version}/frontend-build.zip; \
            unzip -qq /tmp/inventree-frontend-build.zip -d /inventree/src/src/backend/InvenTree/web/static/web; \
            rm -f /tmp/inventree-frontend-build.zip
```

**Apply**:

```sh
appjail apply <jail> apply-frontend.makejail
```

**Comment by gjvanderheiden** [comment]
Thank you, that is really nice. I haven't seen that feature of appjail yet.

So I tried it, same result as my manual attempts, blank browser screen.

Looked into the developer view of the browser and it turns out it needs the contents of that zip in `/inventree/data/static`, so nginx can access it. I really don't understand why this stuff is put in the backend portion (seen from the debian script install on inventree), when clearly it is frontend stuff.

Today I also saw `invoke frontend-download`, not sure what it does, but the description seems to do just the right thing. Only Inventree's `invoke` command does not know ngnix. So maybe it needs some copying / moving to `/inventree/data/static` too. But I'll come back when I tested a bit more and see what `invoke frontend-download` does.

**Comment by gjvanderheiden** [comment]
`invoke frontend-downlad` can be called with `invoke update` if you enable it with a argument. Got that from `src/tasks.py`
Running `invoke frontend-download --tag 0.17.7`  crashes, because it expects the target dir to be there. After making the target dir, it does the exact same thing as done with separate command. That is download zip, extract it, throw away zip.

I tried to unzip the contents directly to `/inventree/data/static' but that does not do the trick: I get an error in the browser that the frontend is not installed. So Inventree expects those files in src/backend/.... too.

Long story short: The appjail-director setup needs the contents in `/inventree/data/static' too for ngnix.

**Comment by gjvanderheiden** [comment]
It needs one sub directory named "web" extra on line 86 of Makejail : 
```
mkdir -p /inventree/src/src/backend/InvenTree/web/static/web; \
```
Otherwise invoke frontend-download fails.

**Comment by gjvanderheiden** [comment]
invoke frontend-download fails, because it expects `/inventree/sr/src/backend/InvenTree/web/static/web`. So the last `web` sub directory is missing. Also, for some reason, the command doesn't do anything. It works when I login in the jail and run the invoke command manually.

**Comment by DtxdF** [comment]
It is created: https://github.com/AppJail-makejails/inventree/blob/main/Makejail#L84

Are you using the current Makejail?

**Comment by gjvanderheiden** [comment]
yes, so to clarify:
If I build with app jail-director and set inventree_platform_ui so the new addition in Makejail is actually used, I get a build error for Inventree. If I alter the Makejail locally and add "/web" to the directory being created, it does build, but for some stupid reason the invoke frontend-download doesn't do its job. I get the error as if this command never was executed. If I instead of setting inventree_platform_ui login into the jail and run invoke frontend-download it runs fine. Weird.

**Comment by DtxdF** [comment]
> If I build with app jail-director and set inventree_platform_ui so the new addition in Makejail is actually used, I get a build error for Inventree.

What is the error that appears?

**Comment by gjvanderheiden** [comment]
Can't find any collection named 'tasks'!
cp: /inventree/src/src/backend/InvenTree/web/static/web: No such file or directory

**Comment by gjvanderheiden** [comment]
Scenario I tried: 
1. appjail image list gives no entries
2. appjail jail list gives no entries
3. Using appjail-director with instructions from the main md file, with the invoke update once recommendation, with argument 'inventree_platform_ui: True' and some changes for the locale and hostname. Only appjail-director is different, this is the appjail-director.yml:
```
options:
  - virtualnet: ':<random> default'
  - nat:

services:
  inventree:
    name: inventree
    makejail: gh+AppJail-makejails/inventree
    volumes:
      - inventree-data: /inventree/data
    environment:
      - INVENTREE_ADMIN_USER: !ENV '${INVENTREE_ADMIN_USER}'
      - INVENTREE_ADMIN_PASSWORD: !ENV '${INVENTREE_ADMIN_PASSWORD}'
      - INVENTREE_ADMIN_EMAIL: !ENV '${INVENTREE_ADMIN_EMAIL}'
      - INVENTREE_CACHE_HOST: inventree-redis
      - INVENTREE_DEBUG: True
      - INVENTREE_DB_ENGINE: mysql
      - INVENTREE_DB_HOST: inventree-mariadb
      - INVENTREE_DB_PORT: 3306
      - INVENTREE_DB_NAME: inventree
      - INVENTREE_DB_USER: inventree
      - INVENTREE_DB_PASSWORD: !ENV '${INVENTREE_DB_PASSWORD}'
      - INVENTREE_BACKGROUND_WORKERS: 6
      - INVENTREE_BACKGROUND_TIMEOUT: 90
      - INVENTREE_BACKGROUND_MAX_ATTEMPTS: 90
      - INVENTREE_TIMEZONE: 'Europe/Amsterdam'
      - INVENTREE_ALLOWED_HOSTS: '*'
      - INVENTREE_SITE_URL: 'http://macmini.localdomain'
      - INVENTREE_PLUGINS_ENABLED: True
    arguments:
      - inventree_platform_ui: True
      - inventree_tag: 14.2
      - inventree_gunicorn_conf: !ENV '${INVENTREE_GUNICORN_CONF}'
    options:
      - healthcheck: 'health_cmd:jail:/inventree/init/check.sh "recover_cmd:jail:su -l inventree -c /inventree/init/restart.sh"'
    scripts:
      - type: local
        text: 'service appjail-health onerestart'
  db:
    name: inventree-mariadb
    makejail: gh+AppJail-makejails/mariadb
    priority: 97
    arguments:
      - mariadb_tag: 14.2-114
      - mariadb_user: inventree
      - mariadb_password: !ENV '${INVENTREE_DB_PASSWORD}'
      - mariadb_database: inventree
      - mariadb_root_password: !ENV '${INVENTREE_DB_ROOT_PASSWORD}'
    volumes:
      - db: /var/db/mysql
      - db-done: /.mariadb-done
  cache:
    name: inventree-redis
    makejail: gh+AppJail-makejails/redis
    priority: 98
  reverse-proxy:
    name: inventree-nginx
    makejail: gh+AppJail-makejails/nginx
    arguments:
      - nginx_tag: 14.2
    options:
      - copydir: !ENV '${PWD}/copydir-files'
      - file: /usr/local/etc/nginx/nginx.conf
      - expose: 80
    priority: 100
    volumes:
      - inventree-static: /usr/local/www/inventree/static
      - inventree-media: /usr/local/www/inventree/media

volumes:
  inventree-data:
    device: ./volumes/inventree/data
    owner: 1001
    group: 1001
  inventree-static:
    device: ./volumes/inventree/data/static
  inventree-media:
    device: ./volumes/inventree/data/media
  inventree-locale:
    device: ./volumes/inventree/data/locale
    owner: 1001
    group: 1001
  inventree-i18n:
    device: ./volumes/inventree/data/i18n
    owner: 1001
    group: 1001
  inventree-done:
    device: ./volumes/inventree/done
  db:
    device: ./volumes/mariadb/db
    owner: 88
    group: 88
  db-done:
    device: ./volumes/mariadb/done
```
4. run appjail-director up

Expected: build and run 4 jails for inventree

Result: Creating inventree (inventree) fails:
```
Starting Director (project:inventree) ...
Creating db (inventree-mariadb) ... Done.
Creating cache (inventree-redis) ... Done.
Creating inventree (inventree) ... FAIL!
```
.../inventree/makejail.log:
```
...
processing file django.po in /inventree/src/src/backend/InvenTree/locale/nl/LC_MESSAGES
processing file django.po in /inventree/src/src/backend/InvenTree/locale/sv/LC_MESSAGES
processing file django.po in /inventree/src/src/backend/InvenTree/locale/es_MX/LC_MESSAGES
InvenTree translation coverage: 28%
Can't find any collection named 'tasks'!
cp: /inventree/src/src/backend/InvenTree/web/static/web: No such file or directory```

**Comment by gjvanderheiden** [comment]
Other scenario I tried: 
1. appjail image list gives no entries
2. appjail jail list gives no entries
3. Checkout github AppJail-makejails/inventree in /root/inventree-build
4. Add "/web" to the mkdir -p command on line 86
```
    RAW if [ "${inventree_platform_ui}" != 0 ]; then
        CMD --juser inventree inventree_version=`sh -c "cd ~/src; invoke version | grep -Ee '^InvenTree   ' | cut -d' ' -f4"`; \
            mkdir -p /inventree/src/src/backend/InvenTree/web/static/web; \
            invoke frontend-download -t "${inventree_version}"; \
            cp -a /inventree/src/src/backend/InvenTree/web/static/web /inventree/data/static
    RAW fi
```
5. Alter director yml to use the altered version of makejail 
```
...
services:
  inventree:
    name: inventree
    makejail: /root/inventree-build/Makejail
...
    arguments:
      - inventree_platform_ui: True
      - inventree_tag: 14.2
...
```
6. Run `appjail-director up`
7. Start browser with http://[your server name]/platform

Expected:
The react ui

Result:
Same result as if `inventree_platform_ui' would not been set or 0: Error in the browser
```
INVE-E1 - No frontend included

The frontend bundle could not be found. Please check that your deployment method includes the bundle or check the FAQ.
Install method: None
```
Also login into the jail reveals an empty /inventree/src/src/backend.../web dir.

[makejail.log](https://github.com/user-attachments/files/19428492/makejail.log)
[scripts.log](https://github.com/user-attachments/files/19428493/scripts.log)
[start.log](https://github.com/user-attachments/files/19428491/start.log)
